iris-ror-bootcamp/config/routes.rb
Rails.application.routes.draw do  
  root "home_page#index"  
  devise_for :users  
  get 'login'    , to: 'home_page#login'  
  get 'register' , to: 'home_page#register' 
  get 'logout'   , to: 'home_page#logout' 
    resources :forms , only: [:index , :show , :new , :create  ,   :edit  ,:update    ] do 
        member do  
            get 'new_response'  
            get 'responses' 
            get 'deleteform'
        end 
    end 
    resources :responses  , only: [:index , :create  ]       
end  

iris-ror-bootcamp/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
     # Here in the function, we are not sure if the user is logged in or not
     # Public Permissions can be defined here 
     can :read, Form, public: true

     return unless user.present?
     # At this point we know that the user is logged in
     # A logged in user perform any action on any form that they own
     can :manage, Form, user: user

     return unless user.superuser?
     # At this point we know that the user is a superuser
     # A superuser is allowed to do everything
     can :manage, :all
  end
end 

iris-ror-bootcamp/app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :response
  belongs_to :form_field  

  scope :by_form_field  ,   -> (form_field_id) { where( form_field_id: form_field_id)}   

end

iris-ror-bootcamp/app/models/form.rb
class Form < ApplicationRecord 
=begin 
    has_many :form_field     
    has_many :response    

     was unable to destroy the form , found out that when model has 'has_many' then 
     I had to use , "dependent: :destroy" which tells the ruby to delete the associated records  , when this will be destoyed  
=end  

belongs_to :user 
 
has_many :form_fields  , dependent: :destroy
has_many :responses  , dependent: :destroy  
has_many :sections , dependent: :destroy   

scope :recent, -> { order(created_at: :desc)}   
#scope :by_title, ->(title) {where('name ILIKE ?' ,  "%#title%" )} --> not working 

end

iris-ror-bootcamp/app/models/form_field.rb
class FormField < ApplicationRecord
  belongs_to :form
  belongs_to :section
  has_many :answers  ,  dependent: :destroy
  has_many :form_field_options ,   dependent: :destroy  

  enum field_type: { 
    radio: 0 ,
    checkbox: 1 , 
    text: 2  
  }   
  

  scope :by_form , ->(form_id) {where( form_id: form_id  ) }  #selecting  by form_id  

  scope :by_field_type , ->(field_type) { where( field_type: field_type )}  

 end

iris-ror-bootcamp/app/models/form_field_option.rb
class FormFieldOption < ApplicationRecord
  belongs_to :form_field  
   
end 

iris-ror-bootcamp/app/models/response.rb
class Response < ApplicationRecord
  belongs_to :form 
  belongs_to :section  , optional: true 
  has_many :answers  , dependent: :destroy  
  accepts_nested_attributes_for :answers
end 

iris-ror-bootcamp/app/models/section.rb
class Section < ApplicationRecord 
    belongs_to :form 
    has_many :form_fields ,  dependent: :destroy
    has_many :responses  , dependent: :destroy
end

iris-ror-bootcamp/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable , :timeoutable 
end

iris-ror-bootcamp/app/controllers/forms_controller.rb
class FormsController < ApplicationController 
    
    load_and_authorize_resource 

    #before_action :set_form ,  only: [:show ,   :new_response]  

    def show  
        @form_details = @form  
        @form_fields = FormField.where(form_id: @form.id)     
    end 

    def index 
        #@forms = Form.all  
    end    

    def new_response  
        @response = @form.responses.build  

        @form_fields = FormField.where(form_id: @form.id )  
        
        

        @form_fields.each do |form_field| 
            @response.answers.build(form_field: form_field )
        end 
    end  


    def new 
        if user_signed_in? 
        @form  = Form.new 
        else 
        redirect_to root_path ,  notice: 'You have to sign in to create a form'
        end 
    end  

    def create   
        @form = Form.new(form_params.merge(user_id: current_user.id)) 
        if @form.save  
        redirect_to root_path  , notice: 'The form was created successfully'
        else  
        Rails.logger.debug(@form.errors.full_messages) 
        flash.now[:notice] = 'Internal server error'  
        render :new  
        end 
    end  


    def deleteform 
        if user_signed_in? && @form.user_id == current_user.id
        @form.destroy 
        redirect_to root_path ,  notice: 'Form was successfully deleted.' 
        else 
        redirect_to root_path , notice: 'Unauthorised access' 
        end 
    end 

    def edit
        if user_signed_in? && @form.user_id == current_user.id  
         @form
        else 
        redirect_to root_path , notice: 'Unauthorised access' 
        end 
    end 

    def update  
        if @form.save 
            redirect_to root_path , notice: 'Form was edited successfully.'
        else 
            render :edit 
        end 
    end 


=begin            
    private 
    def set_form 
        @form = Form.find(params[:id]) 
    end 
=end  

    private 

    def form_params 
        params.require(:form).permit(:name ,  :description ,  :user_id  , :public ) 
    end 

end   

iris-ror-bootcamp/app/controllers/home_page_controller.rb
class HomePageController < ApplicationController 
   


  def index  

    if user_signed_in? 
    @forms = Form.all  
    @public_forms  = @forms.where(public: true)
    @private_forms = @forms.where(public: false) 
    @my_forms  = @forms.where( user_id: current_user.id )   
    else 
      @forms = Form.all
      @public_forms  = @forms.where(public: true)  
    end 
 
  end   

  def login 
    redirect_to  new_user_session_path
  end 

  def register 
    redirect_to new_user_registration_path
  end 

  def logout 
    sign_out(current_user) 
    redirect_to root_path 
  end 

  

end 

iris-ror-bootcamp/app/controllers/responses_controller.rb
class ResponsesController < ApplicationController  

    load_and_authorize_resource 

    def create 
        @response = Response.new(response_params) 

        if @response.save 
            redirect_to  responses_path   
        else 
            flash[:notice] = "failed to save the response" 
            Rails.logger.debug(@response.errors.full_messages)  
            redirect_to  new_response_form_path(@response.form.id) ; 
        end 
    end 

    def index  
         #@responses = Response.all   
    end  

    private 
    def response_params 
        params.require(:response).permit(:form_id  ,answers_attributes: [ :form_field_id   ,    :response_text  ,  :response_radio_choice , response_checkbox_choices: [] ]   )  
    end 


end 

iris-ror-bootcamp/app/helpers/home_page_helper.rb
module HomePageHelper
end

iris-ror-bootcamp/app/views/forms/_form.html.erb
<%= form_with(model: form  ,  local: true ) do |f| %> 
    <div> 
    <%= f.label :name  , 'Name of the form' %> <br/>  
    <%= f.text_field :name %> 
    </div>  
    <div>  
    <%= f.label :description  , 'Description of the form' %> <br/>  
    <%= f.text_field  :description %> 
    </div> 
    <div> 
    <%= f.label  :public , 'Do you want to the form to be public?' %> <br/>  
    <%= f.check_box :public %> 
    </div>  
    <%= f.submit 'Submit' %> 
<% end %> 

iris-ror-bootcamp/app/views/forms/edit.html.erb
<h1> Edit the form </h1> 

<%= render  'form' , form:@form  %>   

iris-ror-bootcamp/app/views/forms/index.html.erb
<body style="background: #0A1828 ; color:wheat  " >
<h1 style="display:block; text-align: center  ; " > Forms </h1>  

<div style ="border: 1px solid white ; min-height: 90vh ; padding: 10px ;  "> 
  
<%   @forms.each do |form| %> 
    <div style ="border: 1px solid white ; padding: 5px ;  "> 
      
      <h2 > <%= form.name %> </h2>  
      <p> Description :  <%= form.description %> </p> 
      <h2 style=""><%= link_to "Go To Form"   , form_path(form) , style:"color:white " %> </h2>
    </div> 
<% end %> 
</ul>  
</div> 
</body>   

iris-ror-bootcamp/app/views/forms/new.html.erb
<h1> Create a new form </h1> 


<div style=" position:relative; left:40px; font-size:x-large; "> 
<%= render 'form' ,  form:@form %> 
</div> 

</div> 

iris-ror-bootcamp/app/views/forms/new_response.html.erb
<body style="background: #0A1828 ; color: wheat ; padding: 0px  10px ; display:flex ; align-items:center ; justify-content:center ; height:100vh" >  

<div style=" border: 1px solid white ; padding: 20px ; border-radius: 8px ; width:90%   "> 

<%= form_with(model: @response  , url: responses_path ,  local: true ) do |f| %>  

    <% @form = Form.find_by(id: @response.form_id ) %> 
     
    <h1 style="text-align: center ; font-size: 24px ;  margin-bottom: 20px;" > <%=  @form.name  %>  form </h1>  
    
    <%= f.hidden_field :form_id ,  value: @form.id %>  

    <% @response.answers.each  do |answer| %> 
        <%= f.fields_for :answers , answer do |a| %>  
        <div class="field" style="margin-bottom:15px;" > 
            <label style="display:block ; font-weight:bold ; margin-bottom:5px "> <%= answer.form_field.field_text %>  </label> 
            
            <% if answer.form_field.field_type == 'radio' %> 
                 <% @options = FormFieldOption.where(form_field_id: answer.form_field.id) %> 
                 <% @options.each do |option| %> 
                    <div style= "margin: 5px 0 ">  
                     <%= a.radio_button :response_radio_choice ,  option.option , style: "margin-right: 5px" %> 
                     <%= a.label  option.option , option.option  %> 
                     </div> 
                 <% end %>      
            
            <% elsif answer.form_field.field_type == 'checkbox' %> 
                 <% @options = FormFieldOption.where(form_field_id: answer.form_field.id) %> 
                 <% @options.each do |option| %> 
                    <div style="margin:5px 0"> 
                      <%= a.check_box :response_checkbox_choices , { multiple: true } ,   option.option ,      nil     %> 
                      <%= a.label option.option , option.option ,style:"margin-left: 5px"  %> 
                    </div> 
                 <% end %>   
            
            <% elsif  answer.form_field.field_type == 'text' %> 
                     <%= a.text_field  :response_text , style:"width:40%  ; padding: 10px "  %> 
            <% end %>  

            <%= a.hidden_field :form_field_id , value: answer.form_field.id %> 

        </div>  
        <% end %> 
    <% end %> 
    
    <%= f.submit "Submit" , style: "width: 100% ; padding : 10px  ; cursor:pointer ;  font-size:16px ; border:none   ; border-radius: 5px ;  background-color: #4CAF50  ; color:white " %>  
<% end %>   
</div> 
</body> 

iris-ror-bootcamp/app/views/forms/show.html.erb
<body style="background: #0A1828 ; color: wheat; display: flex ; justify-content:center ; align-items:center ; min-height: 90vh  " >  
<div> 
<h1> <%= @form_details.name %> </h1> 
<h2>  <%= @form_details.description %> </h2>   
<p> <%=  link_to "Create New Response" , new_response_form_path(@form_details) , style: "color: wheat " %>  </p>  
</div> 
</body> 

iris-ror-bootcamp/app/views/home_page/index.html.erb
<div class="container"> 
<div>      
<h1> Public Forms </h1>     

<% if @public_forms.present? %> 

<%  @public_forms.each do |form| %>   
    <div class="form-unit"> 
     <h2 ><%= form.name %> </h2> 
    <h3> <%= form.description %> </h3>  
    <h3> Status: <%= form.public %> </h3>  
           <%= link_to 'Fill the form'  ,  new_response_form_path(form) %>  
    </div>  

<% end %> 

<% else  %>   

<p> No public forms to display   </p>  

<% end %>  

</div> 


<% if user_signed_in? %>  
<div> 

<div> 

<h1> Private Forms </h1>    

<% if @private_forms.present? %> 

<% @private_forms.each  do |form| %> 
    
    <div class="form-unit"> 
    <h2 > <%= form.name %> </h2> 
    <h3 > <%= form.description %> </h3> 
    <h3> Status: <%= form.public %> </h3> 
    <%=  link_to 'Fill the form' ,  new_response_form_path(form) %>  

    </div> 

<% end %> 

<% else  %>  
 
<p> No private forms to display </p> 

<% end %>  

</div> 

<div> 

<h1> My Forms </h1>    

<% if @my_forms.present? %> 

<% @my_forms.each  do |form| %> 
    
    <div class="form-unit"> 
    <h2> <%= form.name %>   </h2> 
    <h3> <%= form.description %> </h3> 
    <h3> Status: <%= form.public %> </h3> 
    <%=  link_to 'Fill the form' ,  new_response_form_path(form) %> <br/> 
    <%=  link_to 'Delete the form' ,  deleteform_form_path(form) %> <br/> 
    <%= link_to 'Edit the form ' , edit_form_path(form) %> <br/>  
    <%= link_to 'Check out the responses' , responses_form_path(form)      %> 
    </div>  

<% end %> 

<% else  %>  
 
<p> You have not yet created any form. </p> 

<% end %>  

</div>  




<%= link_to 'Create Form' ,  new_form_path , style:"color:white; text-align:center; width:100vw; display:block;"   %>    



</div> 

<% else %> 

<p>Please sign in to create forms or view private forms </p>  

<% end %>  

<div class="session_manager">
 
<% if user_signed_in? %> 
<%= link_to 'Log out' ,  logout_path  %> 
<% else %> 
<%= link_to 'Log in'  ,  login_path %> 
<%= link_to 'Register' ,  register_path %>  
<% end %>   

</div>  

</div> 

iris-ror-bootcamp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Iris Ror Bootcamp" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %> 
    
    

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" , media:"all"  %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <div style="display: flex ; justify-content: space-between  ; padding: 5px  " > 
    <h1> Form Manager App </h1>  
  </div> 
    <p class="notice"> <%= notice %> </p> 
    <p class="alert"> <%= alert %> </p> 
    <%= yield %>
  </body>
</html>

iris-ror-bootcamp/app/views/responses/index.html.erb
<body style="background: #0A1828 ; color: wheat ; padding: 0px  10px" > 
<h1> Responses </h1> 
 
<div style="display:flex ;  flex-wrap: wrap ; justify-content:space-between ;  box-sizing: border-box ; border: 3px solid red ; 
   "   > 
<% @responses.each  do |response|  %>  
    <div style="border: 3px solid #BFA181 ; padding: 10px ;  flex: 0 0 48%  ; margin: 1%  ; box-sizing:  border-box;  
        background:#0A1828; color: yellow ; border-radius: 10px; 
    "  >  
    <% @form = Form.find_by(id: response.form_id) %>
    <h2> Name of the form : <%= @form.name  %></h2>   
    <p>ID of the response : <%=  response.id %></p> 
     <% response.answers.each  do |answer| %>  
      
        
        <%if answer.response_text != nil %>  
        <h3> Name:  <%=     answer.response_text  %>   </h3>  
        <%elsif answer.response_radio_choice != nil %> 
        <h3> Course:    <%= answer.response_radio_choice  %> </h3> 
        <%elsif answer.response_checkbox_choices.present?  %> 
        <h3> Interested in:  </h3> 
        <ol> 
        <% answer.response_checkbox_choices.split(',').each  do  |choice|   %> 
            <li> <h4> <%= choice_ =  choice.gsub(/[\[\]"]/, '')  %>  </h4>  </li>  
        <% end %> 
        </ol> 
        <% end %> 
     
     <% end %>  
    </div>      

<% end %> 
</div>

</body> 